// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/6/2025, 6:19:26 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["/Users/huangjunwei/Desktop/figma-export/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangjunwei/Desktop/figma-export/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangjunwei/Desktop/figma-export/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangjunwei/Desktop/figma-export/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangjunwei/Desktop/figma-export/plugins/**/*.{js,ts,mjs}","/Users/huangjunwei/Desktop/figma-export/composables/**/*.{js,ts,mjs}","/Users/huangjunwei/Desktop/figma-export/utils/**/*.{js,ts,mjs}","/Users/huangjunwei/Desktop/figma-export/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangjunwei/Desktop/figma-export/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/huangjunwei/Desktop/figma-export/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/huangjunwei/Desktop/figma-export/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;